[package]
name = "time-tracker"
version = "0.1.0"
authors = ["Daniel Haehre <dghaehre@gmail.com>"]

[dependencies]
clap = "2.32.0"
ansi_term = "0.11.0"
dirs = "1.0"
serde_json = "1.0.35"
serde = "1.0.84"
serde_derive = "1.0.84"
ctrlc = "3.1.1"
chrono = "0.4"
